ALTER TABLE HISTORIA ADD CONSTRAINT FK_HISTORIA_CONQUISTA FOREIGN KEY(CONQUISTA_ID) REFERENCES CONQUISTA(ID);
ALTER TABLE JOGO ADD CONSTRAINT FK_JOGO_CONQUISTA FOREIGN KEY(CONQUISTA_ID) REFERENCES CONQUISTA(ID);
